[package]
name = "transaction-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ledger-core = { path = "../ledger-core" }

[dev-dependencies]
ed25519-dalek = { version = "=3.0.0", default-features = false, features = ["zeroize"] }
transaction-auth-ed25519 = { path = "../transaction-auth-ed25519" }

[lints]
workspace = true
