#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FinalityError {
    EmptyValidatorSet,
    TooManyValidators,
    NonCanonicalValidatorOrder,
    DuplicateConsensusKey,
    ZeroValidatorWeight,
    TotalWeightOverflow,
    WrongNetwork,
    MembershipEpochMismatch,
    ValidatorSetMismatch,
    CheckpointMismatch,
    EmptyCertificate,
    TooManySignatures,
    NonCanonicalSignatureOrder,
    UnknownValidator,
    InvalidSignature,
    SignedWeightOverflow,
    InsufficientQuorum,
    ProofTooLarge,
    InvalidDomain,
    UnexpectedEnd,
    TrailingBytes,
}
