#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StateSyncError {
    EmptyManifest,
    TooManyChunks,
    ChunkTooLarge,
    SnapshotTooLarge,
    NonCanonicalChunkLayout,
    TotalSizeMismatch,
    WrongNetwork,
    UnsupportedProtocol,
    FinalityProofTooLarge,
    InvalidFinalityProof,
    ProviderWrongNetwork,
    ProviderEpochMismatch,
    ProviderRoleNotAllowed,
    UnknownChunk,
    ChunkLengthMismatch,
    ChunkHashMismatch,
    StorageFailure,
    StoredChunkCorrupt,
    ProgressOverflow,
    SyncIncomplete,
    StateRootMismatch,
}
