[package]
name = "receipt-index-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ledger-core = { path = "../ledger-core" }
ledger-runtime-core = { path = "../ledger-runtime-core" }
state-sync-core = { path = "../state-sync-core" }

[lints]
workspace = true
