use crate::Nonce;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum LedgerError {
    AssetAlreadyExists,
    AssetNotFound,
    WrongNetwork,
    Unauthorized,
    InvalidAuthorizationSet,
    InvalidSignature,
    InvalidSymbol,
    InvalidDecimals,
    InvalidAmount,
    EmptyBatch,
    BatchTooLarge,
    NonCanonicalGenesisAssets,
    NonCanonicalGenesisBalances,
    UnexpectedGenesisBacking,
    NonCanonicalSnapshot,
    SnapshotUnknownAsset,
    SnapshotSupplyMismatch,
    SnapshotPolicyViolation,
    SnapshotOperationMismatch,
    FeeSponsorshipNotApplicable,
    SameAccount,
    AssetNotTransferable,
    AssetNotMintable,
    BackingNotApplicable,
    AccountFrozen,
    AccountCannotSend,
    AccountCannotReceive,
    InsufficientBalance,
    NonceMismatch { expected: Nonce, actual: Nonce },
    ArithmeticOverflow,
    SupplyCapExceeded,
    BackingExceeded,
    BackingDeficit,
}
